controllers/ClientController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Client;
use app\models\SearchClient;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ClientController implements the CRUD actions for Client model.
 */
class ClientController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Client models.
     * @return mixed
     */
    public function actionIndex()
    {
        if(!Yii::$app->user->isGuest){
            $searchModel = new SearchClient();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }else{
            throw new \yii\web\ForbiddenHttpException;
        } 
    }

    /**
     * Displays a single Client model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        if(!Yii::$app->user->isGuest){
            $model = $this->findModel($id);
            $id = Yii::$app->user->identity->user_id;
            if($model->user_id == $id){
                return $this->render('view', [
                    'model' => $model,
                ]);
            }else{
                throw new \yii\web\ForbiddenHttpException;
            } 
        }else{
            throw new \yii\web\ForbiddenHttpException;
        } 
    }

    /**
     * Creates a new Client model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if(!Yii::$app->user->isGuest){
            $model = new Client();
            if ($model->load(Yii::$app->request->post()) ) {
                $model->user_id = Yii::$app->user->identity->user_id;
                $model->save();
                return $this->redirect(['view', 'id' => $model->client_id]);
            }

            return $this->render('create', [
                'model' => $model,
            ]);
        }else{
            throw new \yii\web\ForbiddenHttpException;
        } 
    }

    /**
     * Updates an existing Client model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        if(!Yii::$app->user->isGuest){
            $model = $this->findModel($id);
            $id = Yii::$app->user->identity->user_id;
            if($model->user_id == $id){
                if ($model->load(Yii::$app->request->post()) && $model->save()) {
                    return $this->redirect(['view', 'id' => $model->client_id]);
                }
                return $this->render('update', [
                    'model' => $model,
                ]);
            }else{
                throw new \yii\web\ForbiddenHttpException;
            } 
        }else{
            throw new \yii\web\ForbiddenHttpException;
        } 
    }

    /**
     * Deletes an existing Client model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        if(!Yii::$app->user->isGuest){
            $model = $this->findModel($id);
            $id = Yii::$app->user->identity->user_id;
            if($model->user_id == $id){
                $model = $this->findModel($id);
                $model->is_deleted = 1;
                $model->save(false);
                return $this->redirect(['index']);
            }else{
                throw new \yii\web\ForbiddenHttpException;
            }
        }else{
            throw new \yii\web\ForbiddenHttpException;
        } 
    }

    /**
     * Finds the Client model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Client the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Client::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\Users;
use yii\widgets\ActiveForm;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
   /*  public function actionDashboard()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['invoice/index']);
        }else{
            return $this->redirect(['site/login']);
        }
    } */
    public function actionIndex()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['invoice/index']);
        }else{
            return $this->redirect(['site/login']);
        }
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        $newuser = new Users();
        $newuser->scenario = Users::SCENARIO_REGISTER;
        if(Yii::$app->request->isAjax && $newuser->load(Yii::$app->request->post())){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($newuser);
        }

        if ($newuser->load(Yii::$app->request->post())) {
            $decrypt_pass = $newuser->password;
            $newuser->password = Yii::$app->getSecurity()->generatePasswordHash($newuser->password);
            $newuser->password_repeat = $newuser->password;
            if($newuser->save()){
                $model->username = $newuser->email;
                $model->password = $decrypt_pass;
                $model->login();
                return $this->redirect(['users/update']);
            }
            //return $this->goBack();
        }
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['invoice/index']);
        }
        
        return $this->render('login', [
            'model' => $model,
            'newuser' => $newuser,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->redirect(['login']);
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
}

controllers/UsersController.php
<?php

namespace app\controllers;

use app\models\ResetPassword;
use Yii;
use app\models\Users;
use yii\web\UploadedFile;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * UsersController implements the CRUD actions for Users model.
 */
class UsersController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
/*     public function actionIndex()
    {
        $searchModel = new SearchUsers();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    } */

    /**
     * Displays a single Users model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        if(!Yii::$app->user->isGuest){
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }else{
            throw new \yii\web\ForbiddenHttpException;
        } 
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
/*     public function actionCreate()
    {
        $model = new Users();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->user_id]);
        }
        return $this->render('create', [
            'model' => $model,
        ]);
    }
 */
    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate()
    {
        if(!Yii::$app->user->isGuest){

            $id = Yii::$app->user->identity->user_id;
            $model = $this->findModel($id);

            if ($model->load(Yii::$app->request->post()) ) {
                $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
                $model->upload();
                $model->save();
                return $this->redirect(['view','id' => $model->user_id]);
            }

            return $this->render('update', [
                'model' => $model,
            ]);
        }else{
            throw new \yii\web\ForbiddenHttpException;
        } 
    }
    public function actionChangePassword()
    {
        if(!Yii::$app->user->isGuest){
        
            $alert = 0;
            $id = Yii::$app->user->identity->user_id;
            $model = $this->findModel($id);
            $password = $model->password;
            $model->scenario = Users::SCENARIO_PASSWORD_CHANGE;
            if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())){
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            
            if ($model->load(Yii::$app->request->post())) {
                if(!Yii::$app->getSecurity()->validatePassword($model->old_password, $password)){
                    $model->addError('old_password', 'Incorrect password');
                    $model->password = "";
                    $model->password_repeat = "";
                }else{
                    $model->password = Yii::$app->getSecurity()->generatePasswordHash($model->password);
                    $model->password_repeat = $model->password;
                    if($model->save()){
                        $alert = 1;
                        
                    }
                }
                //return $this->redirect(['view','id' => $model->user_id]);
            }
            $model->password = "";
            $model->password_repeat = "";
            $model->old_password = "";
            return $this->render('change-password', [
                'model' => $model,
                'alert' => $alert,
            ]);
        }else{
            throw new \yii\web\ForbiddenHttpException;
        } 
    }
    public function actionForgotPasswordReset()
    {
        $alert = 0;
        $model = new Users();
        if(Yii::$app->request->get('user') && Yii::$app->request->get('email')){
            $email = Yii::$app->request->get('email');
            $hash = Yii::$app->request->get('user');
            $check_date = date("Y-m-d H:i:s", strtotime('-15 minutes'));
            $result = ResetPassword::find()
                            ->where(['email' => $email])
                            ->andWhere(['reset_hash' => $hash])
                            ->andWhere(['>','created_at', $check_date])
                            ->one();
            if($result){
                $model = Users::find()
                            ->where(['email' => $email])
                            ->one();
            }else{
                return $this->render('error');

            }
        }
        $password = $model->password;
        $model->scenario = Users::SCENARIO_FORGOT_PASS;
        if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
        
        if ($model->load(Yii::$app->request->post())) {
                $model->password = Yii::$app->getSecurity()->generatePasswordHash($model->password);
                $model->password_repeat = $model->password;
                if($model->save()){
                    ResetPassword::deleteAll(['email' => $model->email]);
                    $alert = 1;
                }
            //return $this->redirect(['view','id' => $model->user_id]);
        }
        $model->password = "";
        $model->password_repeat = "";
        return $this->render('change-password-rest', [
            'model' => $model,
            'alert' => $alert,
        ]);
    }

    public function actionForgotPassword()
    {
        $email = "";
        $alert = 0;
        if (Yii::$app->request->post("email")) {
           $email = Yii::$app->request->post("email");
           $user = Users::find()
                            ->where(['email' => $email])
                            ->one();
            $check_date = date("Y-m-d H:i:s", strtotime('-15 minutes'));
            $links = ResetPassword::find()
                                ->where(['email' => $email])
                                ->andWhere(['>','created_at', $check_date])
                                ->all();
            if(!$user){
                $alert = 1;
            }else if($links){
                $alert = 3;
            }else{
                
                $string = microtime() . $user->user_id;
                $hash = Yii::$app->getSecurity()->generatePasswordHash($string);
                $url = "https://invoicetelly.in/web/index.php?r=users/forgot-password-reset&user=$hash&email=$email";
                $result = Yii::$app->mailer->compose('reset_template', ['url' => $url])
                                ->setFrom('invoicetelly@gmail.com')
                                ->setTo($email)
                                ->setSubject('Reset password to Invoice Telly account')
                                ->send();
                if($result){
                    $alert = 2;
                    $reset_password = new ResetPassword();
                    $reset_password->email = $email;
                    $reset_password->reset_hash = $hash;
                    $reset_password->save();
                }else{
                    $alert = 4;
                }
                //send email
            }
           
        }
     
        return $this->render('forgot-password',[
            'alert' => $alert,
        ]);
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        if(!Yii::$app->user->isGuest){

            $this->findModel($id)->delete();

            return $this->redirect(['index']);
        }else{
            throw new \yii\web\ForbiddenHttpException;
        } 
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="icon" href="img/fav.png" type="image/gif" sizes="16x16">
    <link rel="manifest" href="manifest.json">

    <?php $this->head() ?>
    <style>
        .navbar-default {
            border: none;
        }
        .navbar-default .navbar-nav > .active > a, .navbar-default .navbar-nav > .active > a:hover, .navbar-default .navbar-nav > .active > a:focus {
            /* text-decoration: underline; */
            /* color: #555; */
            border-bottom: 2px solid red;
            background-color: #5550;
            font-weight: bold;
        }
        .line{
            border: 2px solid red;
            background-color: red;
            width: 50px;
            margin: 15px auto;

        }
    </style>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php 
        $menu = [];
        $user = [];
        $user[] = ["label" => "Business Profile","url" => ['users/update'], "icon" => "fab fa-free-code-camp",'linkOptions' => ['data-method' => 'post']];
        $user[] = ["label" => "Reset Password","url" => ['users/change-password'], "icon" => "fab fa-free-code-camp",'linkOptions' => ['data-method' => 'post']];
        $user[] = ["label" => "Logout","url" => ['site/logout'], "icon" => "fab fa-free-code-camp",'linkOptions' => ['data-method' => 'post']];
        if(Yii::$app->user->isGuest){
            $menu[] = ["label" => "Login","url" => ['site/login'], "icon" => "fab fa-free-code-camp"];
        }else{
            //$menu[] = ["label" => "Dashboard","url" => ['site/dashboard'], "icon" => "fab fa-free-code-camp"];
            $menu[] = ["label" => "Invoice","url" => ['invoice/index'], "icon" => "fab fa-free-code-camp"];
            $menu[] = ["label" => "Clients","url" => ['client/index'], "icon" => "fab fa-free-code-camp",'linkOptions' => ['data-method' => 'post']];
            $menu[] = ["label" => "Report","url" => ['invoice/report'], "icon" => "fab fa-free-code-camp",'linkOptions' => ['data-method' => 'post']];
            $menu[] = [ "label" => "Account", "url" => "#", "items" => $user ];

        }
        

    ?>
    <?php
    NavBar::begin([
        'brandLabel' => Html::img('@web/img/logo.png', ['height'=>'20']),
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => ' navbar-default navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menu
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Invoice Telly <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>
<?php 
    $script = <<< JS
        $(document).ready(function(){
           
        if ('serviceWorker' in navigator) 
        { // 
            navigator.serviceWorker.register('service-worker.js',{
                scope: '.'
            }).then(function(reg) {
                console.log('Successfully registered service worker', reg);
            }).catch(function(err) {
                console.warn('Error whilst registering service worker', err);
            });
        }
    });
JS;
$this->registerJS($script);
?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/print.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="icon" href="img/fav.png" type="image/gif" sizes="16x16">
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
    <?= $content ?>
<?php $this->endBody() ?>
<?php 
    $script = <<< JS
        (window).print();
JS;
//$this->registerJS($script);
?>
</body>
</html>
<?php $this->endPage() ?>